/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Posts API
 * API для управления постами
 * OpenAPI spec version: 1.0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * User role
 */
export type UserDtoUserRole = typeof UserDtoUserRole[keyof typeof UserDtoUserRole];


export const UserDtoUserRole = {
  reader: 'reader',
  author: 'author',
} as const;

export type UserDtoUser = {
  id: number;
  /** @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$ */
  email: string;
  /** User role */
  role: UserDtoUserRole;
};

export interface UserDto {
  /** JWT access token */
  accessToken: string;
  user: UserDtoUser;
}

export interface LoginDto {
  /**
   * User email
   * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email: string;
  /**
   * User password
   * @minLength 1
   */
  password: string;
}

/**
 * User role
 */
export type RegisterDtoRole = typeof RegisterDtoRole[keyof typeof RegisterDtoRole];


export const RegisterDtoRole = {
  reader: 'reader',
  author: 'author',
} as const;

export interface RegisterDto {
  /**
   * User email
   * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email: string;
  /**
   * Password with at least one letter and one number
   * @minLength 6
   * @pattern ^(?=.*[A-Za-z])(?=.*\d)
   */
  password: string;
  /** User role */
  role?: RegisterDtoRole;
}

export interface CreateCommentDto {
  /**
   * Comment content
   * @minLength 1
   */
  content: string;
}

export const getPostsAPI = (axiosInstance: AxiosInstance = axios.default) => {
/**
 * @summary Create a new post
 */
const postsControllerCreate = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/posts`,undefined,options
    );
  }

/**
 * @summary Get all posts
 */
const postsControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/posts`,options
    );
  }

/**
 * @summary Get post by ID
 */
const postsControllerFindOne = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(
      `/posts/${id}`,options
    );
  }

/**
 * @summary Update post by ID
 */
const postsControllerUpdate = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.patch(
      `/posts/${id}`,undefined,options
    );
  }

/**
 * @summary Delete post by ID
 */
const postsControllerRemove = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/posts/${id}`,options
    );
  }

/**
 * @summary Get current user
 */
const usersControllerGetMe = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDto>> => {
    return axiosInstance.get(
      `/users/me`,options
    );
  }

/**
 * @summary Get user by ID
 */
const usersControllerGetById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDto>> => {
    return axiosInstance.get(
      `/users/${id}`,options
    );
  }

/**
 * @summary User login
 */
const authControllerLogin = (
    loginDto: LoginDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDto>> => {
    return axiosInstance.post(
      `/auth/login`,
      loginDto,options
    );
  }

/**
 * @summary User registration
 */
const authControllerRegister = (
    registerDto: RegisterDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserDto>> => {
    return axiosInstance.post(
      `/auth/register`,
      registerDto,options
    );
  }

/**
 * @summary Create comment for a post
 */
const commentsControllerCreateComment = (
    postId: number,
    createCommentDto: CreateCommentDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateCommentDto>> => {
    return axiosInstance.post(
      `/comments/${postId}`,
      createCommentDto,options
    );
  }

/**
 * @summary Get comments for a post
 */
const commentsControllerGetComments = (
    postId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateCommentDto[]>> => {
    return axiosInstance.get(
      `/comments/post/${postId}`,options
    );
  }

/**
 * @summary Toggle like for a post
 */
const likesControllerToggleLike = (
    postId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/likes/${postId}`,undefined,options
    );
  }

/**
 * @summary Get likes count for a post
 */
const likesControllerGetLikesCount = (
    postId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(
      `/likes/${postId}/count`,options
    );
  }

return {postsControllerCreate,postsControllerFindAll,postsControllerFindOne,postsControllerUpdate,postsControllerRemove,usersControllerGetMe,usersControllerGetById,authControllerLogin,authControllerRegister,commentsControllerCreateComment,commentsControllerGetComments,likesControllerToggleLike,likesControllerGetLikesCount}};
export type PostsControllerCreateResult = AxiosResponse<void>
export type PostsControllerFindAllResult = AxiosResponse<void>
export type PostsControllerFindOneResult = AxiosResponse<void>
export type PostsControllerUpdateResult = AxiosResponse<void>
export type PostsControllerRemoveResult = AxiosResponse<void>
export type UsersControllerGetMeResult = AxiosResponse<UserDto>
export type UsersControllerGetByIdResult = AxiosResponse<UserDto>
export type AuthControllerLoginResult = AxiosResponse<UserDto>
export type AuthControllerRegisterResult = AxiosResponse<UserDto>
export type CommentsControllerCreateCommentResult = AxiosResponse<CreateCommentDto>
export type CommentsControllerGetCommentsResult = AxiosResponse<CreateCommentDto[]>
export type LikesControllerToggleLikeResult = AxiosResponse<unknown>
export type LikesControllerGetLikesCountResult = AxiosResponse<unknown>
